# Generated by Django 5.2.12 on 2026-07-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_detallecompra'),
        ('ia', '0002_modeloentrenado'),
        ('inventario', '0007_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('descartada', 'Descartada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('compra_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencia_origen', to='compras.compra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_compra', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Sugerencia de Compra',
                'verbose_name_plural': 'Sugerencias de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.PositiveIntegerField()),
                ('costo_unitario_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alerta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_generadas', to='ia.alertareabastecimiento')),
                ('sugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ia.sugerenciacompra')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_compra_detalle', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Sugerencia de Compra',
                'verbose_name_plural': 'Detalles de Sugerencia de Compra',
                'ordering': ['id'],
                'unique_together': {('sugerencia', 'variante')},
            },
        ),
    ]
