# Generated by Django 5.2.12 on 2026-07-06 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_minimo_acumulado', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Fidelización',
                'verbose_name_plural': 'Configuración de Fidelización',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_fidelizacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BeneficioFidelizacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_fidelizacion', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficio_fidelizacion', to='venta.venta')),
            ],
            options={
                'verbose_name': 'Beneficio de Fidelización Mensual',
                'verbose_name_plural': 'Beneficios de Fidelización Mensual',
                'unique_together': {('usuario', 'periodo')},
            },
        ),
    ]
